### ISSUE TITLE
Errors when another zypper is running

### ISSUE THREAD

**Issue by esbjerg** [voxpupuli/puppet-zypprepo#12]
We are using your puppet module for handling zypper related things. Quite often we get errors like this one.

```
Nov 25 02:23:39 ahjmysql01b puppet-agent[19940]: (/Stage[main]/Patchagent::Patchme/Package[tdch-tools-patchme]) Could not evaluate: Could not get latest version: Execution of '/usr/bin/zypper list-updates' returned 4: System management is locked by the application with pid 19914 (zypper).
```

Would it be possible for you to create a work-around for this. Fx. have a retry after some seconds or a setting to ignore errors when another zypper has locked the database.

**Comment by tuxmea** [comment]
This is the behavior of the package resource type and unrelated to the zypprepo type.
The zypprepo type only creates zypper repository information (usually in /etc/zypp/repos.d/.

If another zypper process is running and puppet can not properly use zypper, this indicates that something is done manually on the system.
Otherwise check if a cron is triggering zypper.

On the next puppet run (when no zypper process is running), the package will be managed.

Can we close this issue as it is unrelated to zypprepo type?
